*Page and Latex Commands*
$\newcommand{\C}{\mathbb{C}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\mP}{\mathcal{P}}
\newcommand{\bp}{\begin{pmatrix}}
\newcommand{\ep}{\end{pmatrix}}
$

In [1]:
# Python Imports
import pandas as pd; import numpy as np

### Profit Focused Decision Making in Competing Restaurants


**Expenditure Estimates**

| (Location, Capacity) | Advertising | Bank Charges | Credit Charges | Insurance | Legal & Accounting | Maintenance | Rent | Supplies | Utilities |
|:-:| ---| ---| ---|--- |--- |--- |--- |--- |--- |
|*(1, high)*| - | - | - | - | - | - | - | - | - |
|*(1, medium)*| - | - | - | - | - | - | - | - | - |
|*(1, low)*| - | - | - | - | - | - | - | - | - |
|*(2, high)*| - | - | - | - | - | - | - | - | - |
|*(2, medium)*| - | - | - | - | - | - | - | - | - |
|*(2, low)*| - | - | - | - | - | - | - | - | - |
|*(3, high)*| - | - | - | - | - | - | - | - | - |
|*(3, medium)*| - | - | - | - | - | - | - | - | - |
|*(3, low)*| - | - | - | - | - | - | - | - | - |


**Relocation Matrix Game (Bi-Annual)**

| Restaurant (1,2) | location 1| location 2|  location 3 |
| :-:| ---| ---|--- |
|*high capacity* | sum row 1 | sum row 2| sum row 3|
| *med capacity* | sum row 4 | sum row 5 | sum row 6 |
| *low capcaity* | sum row 7 | sum row 8 | sum row 9 |

**Management Matrix Game (Quarterly)**

| Restaurant # | location 1| location 2|  location 3 |
| :-:| ---| ---|--- |
|*high capacity* |b | c| d|
| *med capacity* |b |c |d |
| *low capcaity* |b |c |d |



**Special of the Day (Daily)**

|  a | b| c|d |
| ---| ---| ---|--- |
|a |b | c| d|
| a|b |c |d |

In [2]:
r1_biannual = pd.read_csv('r1_biannual.csv',index_col=0)
r2_biannual = pd.read_csv('r2_biannual.csv',index_col=0)

r1_biannual.head()

    rent  tax  salary  est gross
1h    -2   -2      -2          4
1m    -2   -2      -2          3
1l    -2   -2      -2          2
2h    -2   -2      -2          4
2m    -2   -2      -2          3

In [3]:
totals = r1_payment.sum(axis=1).tolist()
r1_GM = pd.DataFrame({'location 1':np.array(totals)[0:3], 'location 2':np.array(totals)[3:6], 'location 3':np.array(totals)[6:]})
r1_GM.head()

   location 1  location 2  location 3
0          -2          -2          -2
1          -3          -3          -3
2          -4          -4          -4

How to start the game: Assume that the initial buy in is zero for all buildings. Then adjust this after the first step for whichever building you do not purchase.

### Suggestions

Suppose that we have a fixed percentage of what is being taken by taxes etc like a percentage of loss. Calculate optimal strategy for minimizing loss.

Advertising= 5%

Bank Charges = 2%

Credit Charges = 3 %

Insurance = 20%

Legal & Accounting = 15%

Maintenance = x%

Rent = y%

Supplies = z%

Salaries = s%

Utilities = t%

Taxes = u%

| Restaurant 1 | Advertising | Bank Charges | Credit Charges | Insurance | Legal & Accounting | Maintenance | Rent | Supplies | Salaries | Utilities |
|:-:| ---| ---| ---|--- |--- |--- |--- |--- |--- |--- |
|Service Quality| - | - | - | - | - | - | - | - | - |- |
|Diverse Menu| - | - | - | - | - | - | - | - | - |- |
|Service Time| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |
|*=*| - | - | - | - | - | - | - | - | - |- |

### Daily Specials Game

Suppose two restaurants in pure competition (zero-sum game) with similar menu's (same action set) are offering a daily special on one menu item. If they offer the same special then the customers are evenly divided. If they offer different menu items then they recieve a share of the customer base that is closest to prefering that menu item. For example offering a hamberger in one restaurant vs another restaurant evenly divides the consumer base because they are opposite end of the spectrum. However if offered a burger at one restaurant vs a chicken sandwich at the second restaurant then the first restaurant will win the consumer base because the items are not sufficently diverse for the competition to be pure.


| - | Burger | Chicken Sandwich | Fried Chicken | Spaghetti | Fish Sandwich | IDK | IDK | IDK | Unique Item 1 | Unique Item 2 |
|:-:| ---| ---| ---|--- |--- |--- |--- |--- |--- |--- |
|*Burger* | - | - | - | - | - | - | - | - | - |- |
|*Chicken Sandwich* | - | - | - | - | - | - | - | - | - |- |
|*Fried Chicken* | - | - | - | - | - | - | - | - | - |- |
|*Spaghetti* | - | - | - | - | - | - | - | - | - |- |
|*Fish Sandwich*| - | - | - | - | - | - | - | - | - |- |
|*IDK*| - | - | - | - | - | - | - | - | - |- |
|*IDK*| - | - | - | - | - | - | - | - | - |- |
|*IDK*| - | - | - | - | - | - | - | - | - |- |
|*Unique Item 1*| - | - | - | - | - | - | - | - | - |- |
|*Unique Item 2*| - | - | - | - | - | - | - | - | - |- |